<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="tripteron">
  
<!-- *************************************************** -->
<!-- ******************** Kinematics ******************* -->
<!-- *************************************************** -->
<xacro:include filename="util.xacro"/>
    <link name="world"/>

    <joint name="base_joint" type="fixed">
        <origin xyz="1.5 1.0 0.25" rpy="0 0 0"/>
        <parent link="world"/>
        <child link="base_link"/>        
    </joint>

<!-- URDF relations to IRL are in meters-->
     <link name="base_link">
          <visual>
               <origin xyz="0 0 0" rpy="0 0 0"/>	<!-- Physical Center of robot Endeffector-->
               <geometry>
                    <box size="${pltf_l} ${pltf_w} ${pltf_h}" /> 
               </geometry>
               <material name="magenta"/>
          </visual>
     </link>

<!-- ******************** ARM ONE ******************* -->
     <!-- Base_link to Upper arm  -->
     <joint name="theta1" type="continuous">
          <parent link="base_link"/>
          <child  link="upperArm_one"/>
          <origin xyz="${O_x} -${O_y} -${O_z}" rpy="-${pi/2} -${pi/4} 0"/>  
          <axis   xyz="1 0 0"/>
     </joint>
     
     <link name="upperArm_one">
          <visual>
               <origin xyz="0 0 -${toplimbLng/2}" rpy="0 0 0"/>	 
               <geometry>
                    <cylinder radius="${limbRad}" length="${toplimbLng}"/> 
               </geometry>
               <material name="cyan"/>
          </visual>
     </link>

     <!-- Upper arm to Lower Arm -->
     <joint name="theta2" type="continuous">
          <parent link="upperArm_one"/>
          <child  link="lowerArm_one"/>
          <origin xyz="0 0 -${toplimbLng}" rpy="-${pi/4} 0 0"/>  
          <axis   xyz="1 0 0"/>
     </joint>

     <link name="lowerArm_one">
          <visual>
               <origin xyz="0 0 ${bottomlimbLng/2}" rpy="0 0 0"/>	
               <geometry>
                    <cylinder radius="${limbRad}" length="${bottomlimbLng}"/> 
               </geometry>
               <material name="green"/>
          </visual>
     </link>

     <!-- Lower Arm to rail attachment -->
     <joint name="theta3" type="prismatic">
          <parent link="lowerArm_one"/>
          <child  link="railAttach_one"/>
          <origin xyz="0 0 ${bottomlimbLng}" rpy="-${pi/4} -${pi/4} -${pi/2}"/>  
          <axis   xyz="0 0 1"/>
          <limit lower="${lLim_front}" upper="${uLim_front}" velocity="100" effort="100"/> 
     </joint>
     <link name="railAttach_one">
          <visual>
               <origin xyz="0 -${slider_size/2} 0" rpy="0 0 0"/>	
               <geometry>
                    <xacro:Cube size="${slider_size}"/>
               </geometry>
               <material name="red"/>
          </visual>
     </link>

<!-- ******************** ARM TWO ******************* -->
     <!-- Base_link to Upper arm  -->
     <joint name="theta4" type="continuous">
          <parent link="base_link"/>
          <child  link="upperArm_two"/>
          <origin xyz="${O_x} ${O_y} -${O_z}" rpy="-${pi/2} -${pi/4} 0"/>  
          <axis   xyz="1 0 0"/>
     </joint>
     
     <link name="upperArm_two">
          <visual>
               <origin xyz="0 0 ${toplimbLng/2}" rpy="0 0 0"/>	
               <geometry>
                    <cylinder radius="${limbRad}" length="${toplimbLng}"/> 
               </geometry>
               <material name="cyan"/>
          </visual>
     </link>

     <!-- Upper arm to Lower Arm -->
     <joint name="theta5" type="continuous">
          <parent link="upperArm_two"/>
          <child  link="lowerArm_two"/>
          <origin xyz="0 0 ${toplimbLng}" rpy="-${3*pi/4} 0 0"/>  
          <axis   xyz="1 0 0"/>
     </joint>
     <link name="lowerArm_two">
          <visual>
               <origin xyz="0 0 ${bottomlimbLng/2}" rpy="0 0 0"/>	
               <geometry>
                    <cylinder radius="${limbRad}" length="${bottomlimbLng}"/> 
               </geometry>
               <material name="green"/>
          </visual>
     </link>

     <!-- Lower Arm to rail attachment -->
     <joint name="theta6" type="prismatic">
          <parent link="lowerArm_two"/>
          <child  link="railAttach_two"/>
          <origin xyz="0 0 ${bottomlimbLng}" rpy="-${pi/4} ${pi/4} -${pi/2}"/>  
          <axis   xyz="0 0 1"/>
          <limit lower="${lLim_front}" upper="${uLim_front}" velocity="100" effort="100"/> 
     </joint>
     <link name="railAttach_two">
          <visual>
               <origin xyz="0 -${slider_size/2} 0" rpy="0 0 0"/>	
               <geometry>
                    <xacro:Cube size="${slider_size}"/>
               </geometry>
               <material name="red"/>
          </visual>
     </link>

<!-- ******************** ARM THREE ******************* -->
     <!-- Base_link to Upper arm  -->
     <joint name="theta7" type="continuous">
          <parent link="base_link"/>
          <child  link="upperArm_three"/>
          <origin xyz="-${O_x} -${O_y} -${O_z}" rpy="${pi/3} ${pi/4} -${pi/4}"/>  <!-- Come back later to mess with the yaw  -${pi/4} -->
          <axis   xyz="1 0 0"/>
     </joint>
     
     <link name="upperArm_three">
          <visual>
               <origin xyz="0 0 ${toplimbLng/2}" rpy="0 0 0"/>	
               <geometry>
                    <cylinder radius="${limbRad}" length="${toplimbLng}"/> 
               </geometry>
               <material name="cyan"/>
          </visual>
     </link>

     <!-- Upper arm to Lower Arm -->
     <joint name="theta8" type="continuous">
          <parent link="upperArm_three"/>
          <child  link="lowerArm_three"/>
          <origin xyz="0 0 ${toplimbLng}" rpy="-${2*pi/3} 0 ${pi}"/>  
          <axis   xyz="1 0 0"/>
     </joint>
     <link name="lowerArm_three">
          <visual>
               <origin xyz="0 0 ${bottomlimbLng/2}" rpy="0 0 0"/>	
               <geometry>
                    <cylinder radius="${limbRad}" length="${bottomlimbLng}"/>  
               </geometry>
               <material name="green"/>
          </visual>
     </link>

     <!-- Lower Arm to rail attachment -->
     <joint name="theta9" type="prismatic">
          <parent link="lowerArm_three"/>
          <child  link="railAttach_three"/>
          <origin xyz="0 0 ${bottomlimbLng}" rpy="-${pi/4} ${pi/4} 0"/>  
          <axis   xyz="0 1 0"/>
          <limit lower="${lLim_back}" upper="${uLim_back}" velocity="100" effort="100"/>
     </joint>
     <link name="railAttach_three">
          <visual>
               <origin xyz="-${slider_size/2} 0 0" rpy="0 0 0"/>	
               <geometry>
                    <xacro:Cube size="${slider_size}"/>
               </geometry>
               <material name="red"/>
          </visual>
     </link>

<!-- ******************** ARM FOUR ******************* -->
     <!-- Base_link to Upper arm  -->
     <joint name="theta10" type="continuous">
          <parent link="base_link"/>
          <child  link="upperArm_four"/>
          <origin xyz="-${O_x} ${O_y} -${O_z}" rpy="-${pi/3} ${pi/4} ${pi/4}"/>  <!-- Come back later to mess with the yaw  -0.7854 -->
          <axis   xyz="1 0 0"/>
     </joint>
     
     <link name="upperArm_four">
          <visual>
               <origin xyz="0 0 ${toplimbLng/2}" rpy="0 0 0"/>	
               <geometry>
                    <cylinder radius="${limbRad}" length="${toplimbLng}"/> 
               </geometry>
               <material name="cyan"/>
          </visual>
     </link>

    <!-- Upper arm to Lower Arm -->
     <joint name="theta11" type="continuous">
          <parent link="upperArm_four"/>
          <child  link="lowerArm_four"/>
          <origin xyz="0 0 ${toplimbLng}" rpy="${2*pi/3} 0 ${pi}"/>  
          <axis   xyz="1 0 0"/>
     </joint>
     <link name="lowerArm_four">
          <visual>
               <origin xyz="0 0 ${bottomlimbLng/2}" rpy="0 0 0"/>	
               <geometry>
                    <cylinder radius="${limbRad}" length="${bottomlimbLng}"/>  
               </geometry>
               <material name="green"/>
          </visual>
     </link>

     <!-- Lower Arm to rail attachment -->
     <joint name="theta12" type="prismatic">
          <parent link="lowerArm_four"/>
          <child  link="railAttach_four"/>
          <origin xyz="0 0 ${bottomlimbLng}" rpy="-${pi/4} ${pi/4} 0"/>  <!-- rpy="${pi/3} ${3*pi/4} -${pi/2}"  |${pi/4} -${pi/2} 0-->
          <axis   xyz="0 0 1"/>
          <limit lower="${lLim_back}" upper="${uLim_back}" velocity="100" effort="100"/>
     </joint>
     <link name="railAttach_four">
          <visual>
               <origin xyz="-${slider_size/2} 0 0" rpy="0 0 0"/>	
               <geometry>
                    <xacro:Cube size="${slider_size}"/>
               </geometry>
               <material name="red"/>
          </visual>
     </link>

 </robot>

